import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF_mbd5W8f-ROSFDuqfTzC-1WDsKxPu_E',
    appId: '1:496228550401:android:9189dc1330688c9387fd00',
    messagingSenderId: '496228550401',
    projectId: 'allowance-budget-tracker',
    storageBucket: 'allowance-budget-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-8g0_GXMBqLJUiAx5xBcRiAC3fha6LLk',
    appId: '1:496228550401:ios:3201dfc9646724ae87fd00',
    messagingSenderId: '496228550401',
    projectId: 'allowance-budget-tracker',
    storageBucket: 'allowance-budget-tracker.firebasestorage.app',
    iosBundleId: 'com.apple.AllowanceBudgetDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-8g0_GXMBqLJUiAx5xBcRiAC3fha6LLk',
    appId: '1:496228550401:macos:placeholder',
    messagingSenderId: '496228550401',
    projectId: 'allowance-budget-tracker',
    storageBucket: 'allowance-budget-tracker.firebasestorage.app',
    iosBundleId: 'com.apple.AllowanceBudgetDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF_mbd5W8f-ROSFDuqfTzC-1WDsKxPu_E',
    appId: '1:496228550401:windows:placeholder',
    messagingSenderId: '496228550401',
    projectId: 'allowance-budget-tracker',
    storageBucket: 'allowance-budget-tracker.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDF_mbd5W8f-ROSFDuqfTzC-1WDsKxPu_E',
    appId: '1:496228550401:linux:placeholder',
    messagingSenderId: '496228550401',
    projectId: 'allowance-budget-tracker',
    storageBucket: 'allowance-budget-tracker.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF_mbd5W8f-ROSFDuqfTzC-1WDsKxPu_E',
    appId: '1:496228550401:web:placeholder',
    messagingSenderId: '496228550401',
    projectId: 'allowance-budget-tracker',
    storageBucket: 'allowance-budget-tracker.firebasestorage.app',
  );
}

TargetPlatform get defaultTargetPlatform {
  if (Platform.isAndroid) return TargetPlatform.android;
  if (Platform.isIOS) return TargetPlatform.iOS;
  if (Platform.isWindows) return TargetPlatform.windows;
  if (Platform.isLinux) return TargetPlatform.linux;
  if (Platform.isMacOS) return TargetPlatform.macOS;
  throw UnsupportedError('Unknown platform');
}
